# Generated by Django 4.0 on 2024-04-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Имя пользователя')),
                ('name', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('user_id', models.IntegerField(unique=True, verbose_name='ID пользователя')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Дата регистрации пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
